### PR TITLE
Update to latest changes in graphics and piston_window crates. Removes some unused dev-dependencies.

### PR DESCRIPTION
**Pull request by mitchmindtree**
**Don't merge yet.**

Since updating, all of the colours in all of the examples have become much lighter:

Before
screen shot 2016-02-13 at 1 42 58 am

After
screen shot 2016-02-13 at 1 41 18 am

It's possible that there might be some other change we have to update to in conrod, but perhaps also possible that there may have been a bug introduced to the graphics or gfx_graphics crates during the update to the latest gfx. Will look into this soon as this should be fixed before merging this PR. Ping @bvssvni

### CODE REVIEW

**Comment by bvssvni** [comment]
I'm getting the brighter color in when updating cube example https://github.com/PistonDevelopers/piston-examples/pull/333.

**Comment by bvssvni** [comment]
@kvark Do you know whether Srgb is enabled by default in the new Gfx design?

**Comment by kvark** [comment]
@bvssvni  yes, it [looks like](https://github.com/gfx-rs/gfx/blob/01b336acdbcc19271d18a5475efa91678b59329f/src/backend/gl/src/lib.rs#L251) it's enabled.

**Comment by bvssvni** [comment]
```
88 glPixelStorei(pname = GL_UNPACK_ALIGNMENT, param = 1)
89 glEnable(cap = GL_FRAMEBUFFER_SRGB)
90 glGenVertexArrays(n = 1, arrays = &1)
```
[all_widgets.trace.zip](https://github.com/PistonDevelopers/conrod/files/129807/all_widgets.trace.zip)

**Comment by mitchmindtree** [comment]
@bvssvni @kvark I'm happy to try fix this - any pointers on where I should look?

**Comment by kvark** [comment]
I looked at the trace (thanks @bvssvni !) and only saw this `glEnable(cap = GL_FRAMEBUFFER_SRGB)` w.r.t. SRGB. If the context is created with SRGB support, then it should be all enabled through the pipeline, if not - then this switch does nothing, IIRC. Either way, I'm not sure what's causing the change in gamma so far.

**Comment by bvssvni** [comment]
The PSO pipelines are here https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/back_end.rs#L25-L43.

Shaders used by all piston-graphics backends: https://github.com/PistonDevelopers/shaders/tree/master/graphics2d.

There is an old link to an article about sRGB https://github.com/PistonDevelopers/piston/issues/1014.

**Comment by kvark** [comment]
I compared `apitrace` captures and can confirm that the previous version had sRGB disabled. Where previously you had to opt-in into sRGB explicitly (and it was disabled otherwise), now this is enabled globally with a premise that if you have an sRGB it should do all the necessary conversions.

Problem partially comes from the fact that our main render target views creation doesn't currently use the requested format to set up the `glutin::WindowBuilder` accordingly. When this gets implemented, requesting `Rgba8` targets will have sRGB disabled.

We (GFX) will address this in https://github.com/gfx-rs/gfx/issues/872 . Piston should also make the sRGB setting a part of `WindowSettings` and be explicit about it.

**Comment by kvark** [comment]
@bvssvni @mitchmindtree our interfaces are ready, but not published yet. Need to implement https://github.com/gfx-rs/gfx/issues/877 first.

**Comment by mitchmindtree** [comment]
Thanks for the updates @kvark!

**Comment by kvark** [comment]
@mitchmindtree @bvssvni 
Ok, I published everything. Here is a short recap of what is related to your issue:
  1. Glutin window now properly transforms the requested format into the builder flags. So if you request `Srgb8` color - it will be gamma corrected. `Rgba8` will not. All the GFX examples are updated to use `Srgb8` now.
  2. Glutin window `init_raw` allows for untyped initialization if you don't know your formats off-hand and  you don't want to store them in an enumeration with strong typing.
  3. Glutin window got `update_size` and `update_size_raw` functions to be called upon window resize instead of ever touching `gfx_device_gl::create_main_targets` like Piston does at the moment.
  4. `SurfaceType` now has `get_alpha_bits` and `get_total_bits` functions.

**Comment by bvssvni** [comment]
@mitchmindtree There are some warnings in Rust nightly that you might want to look at:

```
src/graph/mod.rs:472:28: 472:29 warning: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions., #[warn(invalid_type_param_default)] on by default
src/graph/mod.rs:472     pub fn depth_parent<I, J=NodeIndex>(&self, idx: I) -> Option<J>
                                                ^
src/graph/mod.rs:472:28: 472:29 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/graph/mod.rs:472:28: 472:29 note: for more information, see PR 30742 <https://github.com/rust-lang/rust/pull/30724>
src/graph/mod.rs:480:33: 480:34 warning: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions., #[warn(invalid_type_param_default)] on by default
src/graph/mod.rs:480     pub fn x_position_parent<I, J=NodeIndex>(&self, idx: I) -> Option<J>
                                                     ^
src/graph/mod.rs:480:33: 480:34 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/graph/mod.rs:480:33: 480:34 note: for more information, see PR 30742 <https://github.com/rust-lang/rust/pull/30724>
src/graph/mod.rs:488:33: 488:34 warning: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions., #[warn(invalid_type_param_default)] on by default
src/graph/mod.rs:488     pub fn y_position_parent<I, J=NodeIndex>(&self, idx: I) -> Option<J>
                                                     ^
src/graph/mod.rs:488:33: 488:34 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/graph/mod.rs:488:33: 488:34 note: for more information, see PR 30742 <https://github.com/rust-lang/rust/pull/30724>
src/graph/mod.rs:497:32: 497:33 warning: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions., #[warn(invalid_type_param_default)] on by default
src/graph/mod.rs:497     pub fn position_parents<I, J=NodeIndex>(&self, idx: I) -> PositionParents<J>
                                                    ^
src/graph/mod.rs:497:32: 497:33 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/graph/mod.rs:497:32: 497:33 note: for more information, see PR 30742 <https://github.com/rust-lang/rust/pull/30724>
src/graph/mod.rs:505:30: 505:31 warning: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions., #[warn(invalid_type_param_default)] on by default
src/graph/mod.rs:505     pub fn graphic_parent<I, J=NodeIndex>(&self, idx: I) -> Option<J>
                                                  ^
src/graph/mod.rs:505:30: 505:31 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/graph/mod.rs:505:30: 505:31 note: for more information, see PR 30742 <https://github.com/rust-lang/rust/pull/30724>
src/widget/canvas.rs:107:30: 107:39 warning: private type in public interface, #[warn(private_in_public)] on by default
src/widget/canvas.rs:107 pub type FlowOfSplits<'a> = (Direction, ListOfSplits<'a>);
                                                      ^~~~~~~~~
src/widget/canvas.rs:107:30: 107:39 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/widget/canvas.rs:107:30: 107:39 note: for more information, see the explanation for E0446 (`--explain E0446`)
src/widget/mod.rs:799:12: 799:20 warning: private trait in public interface (error E0445), #[warn(private_in_public)] on by default
src/widget/mod.rs:799         U: UiRefMut,
                                 ^~~~~~~~
src/widget/mod.rs:799:12: 799:20 warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
src/widget/mod.rs:799:12: 799:20 note: for more information, see the explanation for E0446 (`--explain E0446`)
```

**Comment by bvssvni** [comment]
@kvark Thanks! I'll take a look at the updates.

**Comment by mitchmindtree** [comment]
@bvssvni thanks! I'll address those warnings now (I won't worry about `UiRefMut` though as it will be removed in #696).

**Comment by bvssvni** [comment]
I've changed gfx_graphics and piston_window to use Srgb8. Same bright colors on this PR, don't know what is wrong. `piston_window = 0.36.1`

**Comment by kvark** [comment]
@bvssvni this is expected behavior. The default backbuffer is typically sRGB-enabled, so your app was using gamma correction when you got it brighter. Old gfx-0.8 required you to opt-in for the gamma correction regardless of the actual back buffer format. The new gfx_window_glutin got the logic to derive sRGB property off the RTV format that you specify. So if you were just running like that, you'd have sRGB disabled (since you were using `Rgba8` formats before), and the picture would match gfx-0.8. But since you changed the RTV to `Srgb8`, it's still using gamma correction, and the picture didn't change.

Hope I explained it in a readable way... In other words - everything works as expected, and it's up to your application to decide if you need gamma correction or not. Previously, you didn't use it with gfx-0.8.

**Comment by bvssvni** [comment]
@kvark If I understand you correctly, we need to correct the gamma of colors received from piston-graphics in order to use sRGB in 3D rendering?

Opened https://github.com/PistonDevelopers/gfx_graphics/issues/279 and https://github.com/PistonDevelopers/graphics/issues/1034.

**Comment by bvssvni** [comment]
@kvark Forget my comment above. I get it now.

EVERYTHING is sRGB, it's just that most people don't know. See https://github.com/PistonDevelopers/piston/issues/1014.

@mitchmindtree RGBA colors in Conrod are mathematically incorrect. This is true also for `[f32; 4]` in piston-graphics. If we want "mathematically correct" colors, then we should switch to linear color space. See https://github.com/PistonDevelopers/graphics/issues/1034.

**Comment by mitchmindtree** [comment]
@bvssvni I just had a read through the other issues and I think I'd like to keep the `Color` type as it is for now - I don't see any great motivation for us to make such a breaking change, though I'm happy to hear your thoughts if you think otherwise! I'm also happy to convert to whatever color format you'd like to go with for piston-graphics in the `backend/graphics.rs` module - it shouldn't be a problem :+1:

What can I do now to help get this ball rolling? Some of my work is currently blocked on this PR, so I'm keen to do what I can :smile:

**Comment by bvssvni** [comment]
@mitchmindtree We need to switch gfx_texture to `Srgba8` instead of `Rgba8`. Then update gfx_graphics, piston_window and then this PR. This would allow us to unblock your further work, and I can address the other issues related to Gfx changes.

**Comment by bvssvni** [comment]
Forgot one thing: gfx_graphics need to correct the gamma by transforming colors received through the `Graphics` trait to sRGB.

**Comment by bvssvni** [comment]
@mitchmindtree The colors should now be fixed with piston_window 0.37.0 and piston2d-graphics 0.15.0.

**Comment by mitchmindtree** [comment]
Thanks a lot @bvssvni, I just updated and it's back to normal :+1:

**Pull request merged**
