### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/PistonDevelopers/conrod/issues/485

### CODE REVIEW

**Comment by bvssvni** [comment]
@mitchmindtree I'm getting a bug (looks like Cargo) https://github.com/PistonDevelopers/conrod/issues/485

**Comment by mitchmindtree** [comment]
@bvssvni looks like cargo works fine in travis' stable build, but there's still a compilation error in there?

**Comment by TheNeikos** [comment]
It builds for me on nightly `rustc 1.3.0-nightly (912ab64a0 2015-06-25)`

```
neikos@celestias-palace ~/p/r/conrod> git branch
* (HEAD detached at bvssvni/upd)
```

**Comment by bvssvni** [comment]
Weird. Still getting the same error on `rustc 1.3.0-nightly (cb7d06215 2015-06-26)`.

**Comment by bvssvni** [comment]
Could be an OSX issue?

**Comment by TheNeikos** [comment]
```
neikos@celestias-palace ~/p/r/conrod> cargo build
   Compiling bitflags v0.2.1
   Compiling shader_version v0.1.0
   Compiling piston-float v0.1.0
   Compiling libc v0.1.8
   Compiling piston-texture v0.2.1
   Compiling interpolation v0.1.0
   Compiling bitflags v0.1.1
   Compiling bitflags v0.3.0
   Compiling read_color v0.1.0
   Compiling rustc-serialize v0.3.15
   Compiling draw_state v0.1.1
   Compiling piston-viewport v0.1.0
   Compiling vecmath v0.1.1
   Compiling clock_ticks v0.0.5
   Compiling rand v0.3.8
   Compiling clock_ticks v0.0.6
   Compiling json_io v0.1.2
   Compiling num v0.1.25
   Compiling piston2d-graphics v0.3.0
   Compiling pistoncore-input v0.1.0
   Compiling elmesque v0.2.0
   Compiling pistoncore-window v0.1.6
   Compiling pistoncore-event_loop v0.2.2
   Compiling pistoncore-event v0.2.2
   Compiling piston v0.2.2
   Compiling conrod v0.4.0 (file:///home/neikos/projects/rust/conrod)
src/widget/envelope_editor.rs:91:5: 91:34 warning: variant is never used: `CurvePoint`, #[warn(dead_code)] on by default
src/widget/envelope_editor.rs:91     CurvePoint(usize, (f64, f64)),
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
neikos@celestias-palace ~/p/r/conrod> cargo -V
cargo 0.3.0-nightly (c8c1624 2015-06-26) (built 2015-06-26)
neikos@celestias-palace ~/p/r/conrod> rustc -V
rustc 1.3.0-nightly (cb7d06215 2015-06-26)
neikos@celestias-palace ~/p/r/conrod> git branch
* (HEAD detached at bvssvni/upd)
  master 
```

Could be possible.

**Comment by Kagami** [comment]
But travis uses Linux for builds. Btw, one of the builds with exactly same code and settings was successful: https://travis-ci.org/PistonDevelopers/gfx_text/jobs/67791196
While other builds fail: https://travis-ci.org/PistonDevelopers/gfx_text/jobs/68330727

**Pull request merged**
