### PR TITLE
Reorganized assets (fonts & images)

### PR DESCRIPTION
**Pull request by debloper**
Also, nodalUIdemo.png can probably be safely removed from the repo (unless ref'd from elsewhere).

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Thanks for this :)

If you could move the Cargo.png back into the top level that'd be appreciated, as it's not really a conrod asset per say, just a picture of conrod's dependency graph :+1:

And yep, nodalUIdemo.png can definitely be removed.

**Comment by bvssvni** [comment]
@debloper Can you fix the changes mentioned above so we can merge this?

**Comment by debloper** [comment]
Added a new commit, instead of sqashed rebasing - hope that's okay. Wasn't sure which would be more expected from the contrib-doc.

Sorry for the delay, somehow this fell through the cracks... should be good to merge now. :D

**Comment by bvssvni** [comment]
@debloper No problem!

**Pull request merged**
