### PR TITLE
modified Cargo.toml to use the "time" crate instead of the deprecated "clock_ticks" module

### PR DESCRIPTION
**Pull request by kookerus**
I also changed src/lib.rs to use the time module.

### CODE REVIEW

**Comment by kookerus** [comment]
Still some things that need to be fixed, I'll finish that up when I have the time.

**Comment by kookerus** [comment]
Fixed the errors associated with using the time crate. The rest of the errors, as far as I can tell, are unrelated.

**Comment by mitchmindtree** [comment]
Please don't merge this yet, the other breakages are due to  [this commit](https://github.com/PistonDevelopers/conrod/commit/6837e2051e4247561f416a387521e09f793a9c09) being pushed to the master branch without any review or testing. I'm reverting that commit now on a separate branch and will let you know once it's fixed and compiling again.

**Comment by mitchmindtree** [comment]
Ok, a fix has been made via [this PR](https://github.com/PistonDevelopers/conrod/pull/634) so that conrod now builds on stable again.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/conrod/pull/637.

**Pull request closed without merging**
