### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by bvssvni**
* Bumpted to 0.6.0

### CODE REVIEW

**Comment by bvssvni** [comment]
I'm not sure whether this should wait for https://github.com/PistonDevelopers/conrod/pull/508

**Comment by bvssvni** [comment]
I'll merge this now since people are waiting for it.

**Comment by mitchmindtree** [comment]
Thanks @bvssvni , no problem - this doesn't cause any issues :) Sorry it's taken me a bit to get around to #508 - currently working on my business' site but will get back to it asap :+1:

**Comment by bvssvni** [comment]
@mitchmindtree Nice! I am glad it turned out OK.

**Pull request merged**
