### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by stratact**

### CODE REVIEW

**Comment by mitchmindtree** [comment]
TY :smile_cat:

**Comment by stratact** [comment]
We have happiness! :wink:

**Comment by bvssvni** [comment]
Notice that when a dependency increases in the first non-zero number, the library should also increase in the first non-zero number. See https://github.com/PistonDevelopers/piston/issues/931

**Comment by mitchmindtree** [comment]
@bvssvni Haha yep, @stratact  checked with me and I mistakenly said 0.7.6 was ok, but fixed it by changing it to 0.8.0 :+1:

**Comment by bvssvni** [comment]
@mitchmindtree Good :smile:

**Pull request merged**
