### PR TITLE
WIP: Chapter 3 of the guide

### PR DESCRIPTION
**Pull request by pwoolcoc**
I've started writing chapter 3 of the guide, and wanted to open this PR sooner rather than later so I can maybe get some feedback on it earlier than I would just dumping the whole thing on you at once.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Awesome!! This is reading really well so far, thanks so much for kicking it off!

If you have any questions or are unsure about anything, feel free to leave a comment here and I'll be more than happy to help :+1:

**Comment by Tropid** [comment]
It's really nice to read!

I think you're missing the arguments for the `WindowSettings::new()` function, though (line 96). The [API-Documentation](http://docs.piston.rs/piston_window/window/struct.WindowSettings.html?search=#method.new) says it takes two arguments, the title of the window and its size.

**Comment by Michael-F-Bryan** [comment]
How's this PR going? 

The main thing preventing me from picking up conrod is the lack of a "this is how you make a basic GUI" guide. The examples are useful, but are hard to understand and not realistic (I mean, how often does your entire application fit into a single `main()` function?), and pointing new people at walls code isn't very user friendly.

Is there anything I can do to help? In particular, is there a rough plan for what chapter 3 will contain, or what type of app you were planning on making (file explorer, note-taking app, etc)?

**Comment by anderejd** [comment]
Just merge this and keep refining it in other PRs?

**Pull request closed without merging**
