### PR TITLE
Update travis to build a selection of examples

### PR DESCRIPTION
**Pull request by burtonageo**

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Hey, thanks for the PR!

I believe the `cargo test` commands already build the examples meaning this might not be necessary, though I could be wrong! Would you mind checking this?

**Comment by SuperCuber** [comment]
I think `cargo test --examples` is enough. From `cargo help test`: 
```
--examples                   Check that all examples compile
```
So instead of this I suggest adding `--examples` to all `test` lines.

**Comment by mitchmindtree** [comment]
@SuperCuber hmm I think `cargo test --examples` *only* tests compiling the examples, whereas `cargo test` compiles the crate, compiles and runs all tests *and* compiles the examples. I could be wrong though!

**Comment by mitchmindtree** [comment]
Going to close this as I believe the new cases are already covered by the `cargo test` commands. Thanks anyways!

**Pull request closed without merging**
