### PR TITLE
[WIP] Expose widget capturing and mouse_over state

### LINKED ISSUE #611: Provide a `Ui` method that returns whether or not the mouse is over a `Widget`.
Perhaps so that it may be used like:

``` rust
if ui.widget_under_mouse().is_none() {
    // Handle other mouse stuff.
}
```

### PR DESCRIPTION
**Pull request by Drakulix**
Attempt to fix #611 and #612.

Currently does not compile, the reason is this line: https://github.com/Drakulix/conrod/blob/feature/input_feedback/src/widget/drop_down_list.rs#L320

I did as suggested in #611 and made `global_input` private, so this is expected.

I would like to have some feedback regarding how I should attempt to fix this:

- Leave `global_input` public and open a new issue on that subject
- Expose more of `global_input.current` via functions to satisfy the current requirements of `DropDownList` (if yes, what exactly?)
- Refactor `DropDownList` in a way this is not required anymore (if yes, how?)

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Thanks for the PR!

Perhaps the issue could be fixed by providing a `pub fn global_input(&self) -> &input::Global` method? That way we can still provide public access to the `global_input` field while ensuring that the user cannot mutate it and mess up behaviour. Thoughts?

**Comment by Drakulix** [comment]
Of course that's also a good idea, I somehow assumed global_input in itself should be an implementation detail. But if it shall just not be modified, that is of course an easy solution.

Do you still wish to keep the `widget_under/capturing` shortcuts, if they are accessible through `global_input` anyways?

**Comment by mitchmindtree** [comment]
Hmmm good question. I think it might be best to remove the new methods in favour of accessing them via the `current` field. Although the new methods do make access a little easier, providing multiple ways of accessing the same thing almost always leads to confusion heh!

**Comment by Drakulix** [comment]
Done. :smiley:

**Comment by Drakulix** [comment]
Tests fixed.

**Comment by mitchmindtree** [comment]
Thanks for this!

**Pull request merged**
