### PR TITLE
Text box view

### PR DESCRIPTION
**Pull request by dcampbell24**
When support for scissoring is added, just need to scissor the view when the text is drawn.

cc #71

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Nice @dcampbell24 ! Thanks for all your awesome work with TextBox! It's definitely starting to look in far better shape :)

Travis seems fine, going to merge this now :+1:

**Comment by bvssvni** [comment]
Scissoring works with gfx_graphics now. Take a look at the draw_state_test.rs example. If we port the Conrod example to piston_window then we can try it out.

**Comment by dcampbell24** [comment]
@bvssvni I tried porting the counter.rs example over to piston_window and ran into two issues:

1. ui::handle_event expects the event to implement Debug, but PistonWindow does not implement Debug.
2. The Debug constraint can be removed and counter.rs will compile, but no text is drawn to the screen.

See https://github.com/dcampbell24/conrod/tree/counter-piston_window

**Comment by bvssvni** [comment]
@dcampbell24 You need to call `GlyphCache::update` https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/glyph.rs#L72 to create the font textures.

**Pull request merged**
