### PR TITLE
Redesign/upgrade to latest Rust

### PR DESCRIPTION
**Pull request by bvssvni**
Examples are now working.

### CODE REVIEW

**Comment by bvssvni** [comment]
There is still some commented old code and property types left, but examples are working now.

**Comment by bvssvni** [comment]
Looks good. Merging.

**Comment by mitchmindtree** [comment]
Heyyy, nice one @bvssvni :) sorry I haven't been around the last couple days, currently on an easter holiday with the fam, will try to jump on when I can though :+1:

**Comment by bvssvni** [comment]
@mitchmindtree Enjoy your holiday!

**Pull request merged**
