### PR TITLE
Fixed toggle matrix demo in all_widgets example

### PR DESCRIPTION
**Pull request by mitchmindtree**

### CODE REVIEW

**Comment by eddyb** [comment]
Why is conrod using `Box::new` instead of `box`?

**Comment by mitchmindtree** [comment]
No idea! I don't think any of these closures should be boxed anyway, looks like it might've been a "quick fix" that occurred when unboxed closures became the default? I might have a go at unboxing them now and see if I run into any issues.

**Comment by bvssvni** [comment]
@eddyb I thought there was an stabilization issue with `box`.

**Comment by eddyb** [comment]
@bvssvni `Box::new` is just there in case something goes horribly wrong, nobody using nightlies should touch it IMO.

**Pull request merged**
