### PR TITLE
Bump webgpu to 0.8

### PR DESCRIPTION
**Pull request by AlexEne**
I've upgraded webgpu. I can't run all the tests as I'm on windows and don't have `ninja` installed. Hopefully if there's anything wrong the CI will pick it up.

I did run the webgpu backend tests and those were fine.

### CODE REVIEW

**Comment by AlexEne** [comment]
I noticed the fmt failiure. Checking what vulkano version works.

**Comment by AlexEne** [comment]
So in order to fix the build due to the change [here](https://github.com/vulkano-rs/vulkano/blob/8c0630d3c86c82581991d599489a69d83f89c97c/CHANGELOG_VK_SYS.md#version-053-2020-12-26)
> Rename shaderf3264 to shaderFloat64
I need to upgrade to vulkano at at least `0.20` from the current `0.16`. This will take a while and I think I may need some help as I'm not too familiar with vulkan, so if I can cope with some WGPU-RS changes, this is a bit complicated and will take me some time to figure out as a bunch of things have happened in Vulkan in the meantime.

**Comment by mitchmindtree** [comment]
Hey @AlexEne don't stress about the vulkano backend if you don't have the time! While it would be nice to have it out of date, it was broken before this PR and isn't related - happy to leave that for a future fix. See #1409 for some context.

Going to take a look at this now!

**Comment by mitchmindtree** [comment]
When attempting to run the `all_winit_wgpu` example (NixOS, GNOME Wayland, Intel GPU), I'm running into the following validation error during shader module creation:

```
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `shaders/frag.spv`
    Function [1] 'main' is invalid
    Required uniformity of control flow for IMPLICIT_LEVEL in [20] is not fulfilled because of Expression([1])


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:1955:5
```

Looking at the diff, I think it is unlikely this is to do with anything you have changed, as the error is related to validation of the SPIR-V shader which hasn't changed in a while. Likely, this is one of the new validation checks picking up something wrong with old code. Will have a look

**Comment by mitchmindtree** [comment]
It's a bit of a strange one - I've opened an issue here https://github.com/gfx-rs/wgpu-rs/issues/912.

**Pull request closed without merging**
