### PR TITLE
Textbox select

### PR DESCRIPTION
**Pull request by davekong**
Adds support for selecting text with the left mouse button in a TextBox. Related functionality to follow soon.

cc: #71

### CODE REVIEW

**Comment by davekong** [comment]
Some feedback is welcome before I add the rest of the selection related features from #71.

**Comment by bvssvni** [comment]
Looks good.

Rust is going through a lot of breaking changes at the moment, so if we merge this now, the related functionality can be added in another PR with less chaos.

**Comment by davekong** [comment]
OK, sure. I'll wait for the dust to settle before adding the rest.

**Comment by davekong** [comment]
Will add the other changes later in a new PR after conrod is building and the beta is out.

**Pull request merged**
